### ISSUE TITLE
`.max()` (and possibly other aggregation functions) throw an error

### ISSUE THREAD

**Issue by Cellane** [vapor/fluent#541] opened 2018-07-12 02:10 UTC
Before adding new entry to a table, I needed to calculate value for one of the columns/properties (the `order` column), and the value is defined as `MAX(order) + 1`. This lead me to believe that this code would do a good job at solving the problem, and work both for first entry (on an empty table) and subsequent entries:

```swift
func createHandler(
   _ req: Request,
   AData: CreateARequest
) throws -> Future<A> {
    return A.query(on: req)
        .max(\A.order)
        .catchMap { _ in 0 }
        .flatMap { maxOrder in
           let a = A(AData.name, maxOrder + 1)

           return a.save(on: req)
        }
}
```

However, this code throws an “Attempting to call send(...) again before previous invocation has completed.” error, possibly from MySQL/Connection/MySQLConnection.swift:82. The only workaround I was able to think of is the following code, which works fine but is obviously not as pretty:

```swift
func createHandler(
   _ req: Request,
   AData: CreateARequest
) throws -> Future<A> {
    return A.query(on: req)
        .sort(\A.order, .descending)
        .first()
        .unwrap(or: Abort(.internalServerError))
        .map { $0.order }
        .catchMap { _ in 0 }
        .flatMap { maxOrder in
           let a = A(AData.name, maxOrder + 1)

           return a.save(on: req)
        }
}
```

I *think* the error was only thrown when the table itself was empty but I’m not entirely sure at this moment as the issue happened a few days ago for me. Apologies!

Let me know if there’s trouble reproducing the issue, I’m sure I can prepare example project if that would be the case.

**Comment by MrMage** [comment] 2018-07-12 05:12
I think this is a duplicate of #450.

**Comment by Cellane** [comment] 2018-07-12 05:15
Ah, quite likely!

Looking back at #450, it seems like there was an [attempt to fix](https://github.com/vapor/fluent/commit/278581565d956197a8c13e4aea8de3fff7b45510) but I don’t think it helped, or possibly helped but resulted in this (different) error message.

**Comment by tanner0101** [comment] 2018-07-12 15:17
> “Attempting to call send(...) again before previous invocation has completed.” error, possibly from MySQL/Connection/MySQLConnection.swift:82.

If you're seeing that, it's a MySQL bug specifically. A repro that produces that error would be appreciated on https://github.com/vapor/fluent-mysql

**Comment by Cellane** [comment] 2018-07-13 01:22
Submitted an issue there, along with code to reproduce and bit more information!

**Comment by tanner0101** [comment] 2020-05-29 17:07
Dupe of https://github.com/vapor/fluent/issues/450

**Closed by tanner0101** 2020-05-29 17:07 UTC
Labels: bug
