### ISSUE TITLE
Filter by eager loaded field?

### ISSUE THREAD

**Issue by skyweb07** [vapor/fluent#685] opened 2020-05-19 17:20 UTC
Hi guys, I was wondering if there's an option to filter by parent field properties, something like this

<img width="1385" alt="Screenshot 2020-05-19 at 19 20 16" src="https://user-images.githubusercontent.com/747750/82357718-c6db5b80-9a05-11ea-83c8-5a2e9a28ed60.png">

Thanks you

**Comment by tanner0101** [comment] 2020-05-20 15:47
Duplicate of https://github.com/vapor/fluent-kit/issues/227

**Closed by tanner0101** 2020-05-20 15:47 UTC
