### ISSUE TITLE
Feature Request: SQL MERGE (aka UPSERT) capability

### ISSUE THREAD

**Issue by marc-medley** [vapor/fluent#640] opened 2019-07-18 18:12 UTC
Add the SQL MERGE (aka UPSERT) capability to fluent.

https://en.wikipedia.org/wiki/Merge_(SQL)

**Related**

* https://github.com/vapor/fluent-sqlite-driver/issues/23
* https://stackoverflow.com/questions/54389866/using-vapor-fluent-to-upsert-models
* https://stackoverflow.com/questions/57096321/how-to-upsert-multiple-records-at-once-with-vapor-3-postgressql

**Comment by tanner0101** [comment] 2020-02-18 22:24
Duplicate of https://github.com/vapor/fluent-kit/issues/50

**Closed by tanner0101** 2020-02-18 22:24 UTC
