### ISSUE TITLE
Query limit and offset using subscript

### ISSUE THREAD

**Issue by yuriferretti** [vapor/fluent#135] opened 2016-11-27 18:08 UTC
# Enhancement

# Query limit and offset using subscript

* Author(s): [Yuri Ferretti](https://github.com/yuriferretti)
* Status: **[Awaiting review](#rationale)**

## Introduction

Query limits are very useful and could be done in a more concise and readable way using subscript like `User.all()[2..<10]`

## Motivation

Limit and offset are very useful features to control which entries will be fetched from database. Fluent `Query` provides a limit atribute which is responsible for controlling result set entries but setting this attribute everytime we want limit the query can become cumbersome.

## Proposed solution

The idea is to implement a subscript that takes a range as parameter to make query limiting more readable and concise. It will also make developer more familiar with syntax because in swift array slices are obtained in that way.

```swift
subscript(range: Range<Int>) -> Query? 
```

## Code snippets

```swift
// Before
let query = User.query().filter("name", "john")
query.limit = Limit(count: 10, offset: 0)

// After 
let query = User.query().filter("name", "john")[0..<10]

// Before 
let query = User.query().filter("name", "john")
query.limit = Limit(count: 10, offset: 2)

// After 
let query = User.query().filter("name", "john")[2..<12]
```

## Impact

This proposal is only additive and no code changes are required after its implementation.

## Alternatives considered

No alternatives were considered.

**Comment by Casperhr** [comment] 2017-01-03 08:41
Where is now added a limit() func
try Model.query().limit(10).all()

**Comment by kikolobo** [comment] 2017-01-16 05:54
What about offset?

**Comment by yuriferretti** [comment] 2017-01-16 11:25
That is a very nice improvement @Casperhr but I still missing the `offset`. I'm familiar with `Django` development and it provides a very neat [syntax]  (https://docs.djangoproject.com/en/1.10/topics/db/queries/#limiting-querysets) (that inspired my proposal) for limit and offset. Also is worth mentioning Django's ORM is based on querysets which are kinda lazy result list that only  evaluates its underlying SQL query after their elements are accessed. This led me to think about if my proposal should be applied to `Query` entity or to its result set 🤔

**Comment by Casperhr** [comment] 2017-01-16 11:27
let limit = Limit(count: perPage, offset: offset)
  query.limit = limit

We just need a func for offset like limit
@yuriferretti can you do a PR on that?

**Comment by yuriferretti** [comment] 2017-01-16 11:34
@Casperhr a PR for subscript or offset method? I'm asking because I don't think that setting an offset without limit is permitted. So how would the following work?:
```swift
query.offset(5)
```

**Comment by C0deH4cker** [comment] 2017-03-01 11:45
The biggest issue with the subscript proposal is that the range's end is ambiguous. Would the end mean the maximum `id` or would you subtract the range start from the end to compute a limit? In the first case, `query[10..<20]` might only return 2 items if the others in that range have been deleted. In the second case, `query[10..<20]` might return an item with an `id` of 30 or even 100 depending on how many items have been deleted. The issue is that unlike arrays, database rows are sparse and might be missing rows with certain values of `id`. I think @davidvpe's merged PR is the best solution and that a subscript would be more harmful than beneficial.

**Comment by yuriferretti** [comment] 2017-03-01 16:19
@C0deH4cker I see your point, but let me better explain mine
```sql
SELECT * FROM user LIMIT 10 OFFSET 2
```
```sql
SELECT * FROM user WHERE id > 45 LIMIT 10 OFFSET 2
```
Both queries will ask from users persisted in database passing the WHERE clause, ignoring first two results and returning a maximum of 10 results. This has nothing to do with ids or other table columns.
My point is that the query result or `Result set` is a list of database rows matching a given SQL statement and `LIMIT` and `OFFSET` are just like array slicing on this list enforced by DBMS.
So, for me, sounds very natural use subscript the same way array does for slicing the result set.

**Comment by BrettRToomey** [comment] 2017-05-03 12:29
Closing due to inactivity. Feel free to reopen.

**Closed by BrettRToomey** 2017-05-03 12:29 UTC
